### ISSUE TITLE
failed to lunch oregano, 'apps.oregano' is not installed

### ISSUE THREAD

**Issue by niuniuaba** [drahnr/oregano#140]
Hi there, 
I successed to build from source (latest git), but failed to launch oregano with error message:

 GLib-GIO-ERROR **: Settings schema 'apps.oregano' is not installed

P.S. I installed in different directory rather than /usr/local, and set environment variable export XDG_DATA_DIRS before launch.

**Comment by drahnr** [comment]
I recently fixed a warning about exactly that deprecated apps prefix in the schema file. I might have missed a spot though, will have a look at it tonight.
If you need it badly, just have look at the last 10 commits and revert the offending one.
