### ISSUE TITLE
add to macports

### ISSUE THREAD

**Issue by reubano** [drahnr/oregano#144]
Could you please add this to [macports](https://guide.macports.org/chunked/development.creating-portfile.html)?

**Comment by reubano** [comment]
Or better yet, take over the [current port](https://trac.macports.org/browser/trunk/dports/gnome/oregano).

**Comment by drahnr** [comment]
I do not own a mac, I sure have a few colleagues with a mac but I definitely need guidance on doing so.

**Comment by reubano** [comment]
I've never built a macport myself, so I can't be of much help. However, the above links should be able to point you in the right direction.

**Comment by drahnr** [comment]
I need you as my guinea pig for the mac ports I hack together :)

I could maybe do it on Friday, but not promises made.

**Comment by drahnr** [comment]
Just because you never did it does not mean that you can not do it.

**Comment by drahnr** [comment]
To be honest, this is effort that is currently not worth it.

If you can provide a PR I'll happily merge them.
