### ISSUE TITLE
Absolute vertical resolution

### ISSUE THREAD

**Issue by WyRe** [drahnr/oregano#148]
I wish I could resize some windows; I have got Oregano installed on a notebook with a strange resolution (1024x576) and I cannot see bottom of some windows.

http://i.imgur.com/z954yXE.png

Thank so much! :P

**Comment by drahnr** [comment]
I started the ground work for a UI refactor that will take care of that issue.

If I find the time I will convert that dialog in advance.

**Comment by WyRe** [comment]
Thank so much! :D

**Comment by drahnr** [comment]
If your problems persist feel free to reopen :)
