### ISSUE TITLE
Yelp help files are neither built nor installed

### ISSUE THREAD

**Issue by dbevans** [drahnr/oregano#153]
Relative to version 0.82, the current release, oregano 0.83.2.1, neither builds nor installs the corresponding yelp help files from the sources contained in the help subdirectory.  This results in the yelp error

`The URI ‘ghelp:oregano’ does not point to a valid page.`

when the _Help/User's Manual_ menu item is selected.  Suggest you either build and install the help files or remove the menu item.

**Comment by drahnr** [comment]
Good catch. This is indeed a bug.

**Comment by dbevans** [comment]
Thanks.  While you're at it, you might remove the old scrollkeeper (rarian) style doc format.

**Comment by drahnr** [comment]
Can you open a separate ticket for that and elaborate a bit?

**Comment by dbevans** [comment]
Will do.
