### ISSUE TITLE
builddeps should prompt before installing/updating.

### ISSUE THREAD

**Issue by ghedberg** [drahnr/oregano#154]
### Steps to reproduce
1. run builddeps

### Expected behaviour
Tell us what should happen

I should be prompted as to what the installer is intending to install before installing.

### Actual behaviour

The automatic update and install of packages installed a buggy kernel driver on my system causing X to stop working (after reboot).

### Configuration
**Operating system**:  fedora 23 on a HP laptop (i915 is buggy as hell)
```
cat /etc/os-release |grep PRETTY_NAME
```

Essentially I really think that both updating and installing packages with -y and no user prompt is a really bad idea. I guess I should have read the code before running, but I think that it is standard practice to prompt the user to choose if they want to proceed.

The update installed a buggy intel X driver which a few days later when I rebooted, X refused to detect my screens and caused me a couple of hours of backtracking to find what happened (which is not fun to do without a working screen).

**Comment by drahnr** [comment]
Agreed, I did not consider those use cases enough.

**Comment by ghedberg** [comment]
Looks good to me. Thanks
