### ISSUE TITLE
Plot add function (Division not working)

### ISSUE THREAD

**Issue by LukasGibeh** [drahnr/oregano#156]
### Steps to reproduce
1. Simulate circuit
2. File->Add Function in plot window (try "Division")
3. Subtraction will be added instead

### Fix
- ComboBox "Function Type" is never checked

 ```
/src/sheet/plot-add-function.h, l. 131: 
 current->functions = g_list_append (current->functions, func);
 ```
without setting type of `func` before (default value of `SimulationFunctionType`is `FUNCTION_MINUS`

**Comment by drahnr** [comment]
The whole plotting widget is planned to be replaced by github.com/drahnr/goatplot which is supposed to be feature complete within a few weeks.

**Comment by drahnr** [comment]
Please verify
