### ISSUE TITLE
change aur address 

### ISSUE THREAD

**Issue by rezad1393** [drahnr/oregano#158]
the aur package address aur4 is retired and migrated to aur.
please update it in readme file

**Comment by drahnr** [comment]
can you give me the exact link? I did not use the ArchLinux for at least a year
Thanks!

**Comment by rezad1393** [comment]
here :

    Fedora - stable and git or via dnf copr enable drahnr/oregano
    ArchLinux - stable, git

change the link of archlinux
from 
https://**aur4**.archlinux.org/packages/oregano/
to 
https://**aur**.archlinux.org/packages/oregano/
