### ISSUE TITLE
Oregano - Plot: Resolution has to improve

### ISSUE THREAD

**Issue by Michi1994** [drahnr/oregano#172]
### Steps to reproduce
1. open [tryResolution.oregano](https://github.com/drahnr/oregano/files/1025281/tryResolution.oregano.txt)
2. run simultation
3. in the Oregano - Plot, zoom in at 0.24ms to view the oscillations like ![here](https://cloud.githubusercontent.com/assets/23436598/26400750/ddd30020-4082-11e7-98c7-f2fcf1e4cb80.png)

### Expected behaviour
each number on the time axis should not be equal

### Actual behaviour
all numbers on the time axis are equal (0.24ms)

### Configuration
**Operating system**:
```
$ cat /etc/os-release |grep PRETTY_NAME
PRETTY_NAME="Ubuntu 16.10"
```

**Versions**
```
$ oregano --version
Oregano 0.84.1
 Website: https://ahoi.io/projects/oregano
 License: GPLv2/GPLv3
 Main Developer: Bernhard Schuster
$ ngspice --version
ngspice compiled from ngspice revision 26
Written originally by Berkeley University
Currently maintained by the NGSpice Project

Copyright (C) 1985-1996,  The Regents of the University of California
Copyright (C) 1999-2011,  The NGSpice Project
```

**Comment by drahnr** [comment]
Do not invest any work on this other than integrating goatplot!

**Comment by Michi1994** [comment]
I thought about looking for plotting packages before I began to invest work in it. But I thought also that searching for and integrating another package means more work than adding a small beauty feature. So you searched already and found goatplot. That's great. Next time I will begin integrating goatplot as an alternative (user decides which plot window should be used).

**Comment by Michi1994** [comment]
I mean: you wrote goatplot, wow!
