### ISSUE TITLE
Obsolete oregano release

### ISSUE THREAD

**Issue by gtrentalancia** [drahnr/oregano#199]
### Steps to reproduce
1. Visit the release page on github: https://github.com/drahnr/oregano/releases
2. The latest release appears to be v0.83.2.1
3.

### Expected behaviour
There should be a new release which includes the recent AC and Noise analysis features:

https://github.com/drahnr/oregano/commit/4e8c529f22563191978db36bfff654282896ab81

### Actual behaviour
Obsolete latest release is listed in the release page on github.

**Comment by drahnr** [comment]
That is a ci topic, which requires to integrate the `github-release-resource` for `concourse.ci` if the tree-ish is tagged.
