### ISSUE TITLE
ld `gtk_show_uri_on_window ()` missing

### ISSUE THREAD

**Issue by drahnr** [drahnr/oregano#212]
`gtk_show_uri_on_window ()` is new with gtk+ 3.22 
a) ubuntu has an older gtk+ version
b) ubuntu provides a patched gtk+ version which does not provide this

https://developer.gnome.org/gtk3/stable/gtk3-Filesystem-utilities.html#gtk-show-uri-on-window

https://ci.spearow.io/teams/main/pipelines/oregano/jobs/pr-build-pkg-deb/builds/40

@gtrentalancia can you have a look into this?

**Comment by drahnr** [comment]
```
# pkg-config --modversion "gtk+-3.0"
3.18.9
```

```
NAME="Ubuntu"
VERSION="16.04.2 LTS (Xenial Xerus)"
PRETTY_NAME="Ubuntu 16.04.2 LTS"
```

This implies to either use an if/else macro around this or to bump Ubuntu to 17.04

**Comment by gtrentalancia** [comment]
Fixed here:

https://github.com/gtrentalancia/oregano/commit/9dee73babf3c2b83d324be5b2ce7a93e3be2806b

I will now create a pull request for this and another minor improvement.
