### ISSUE TITLE
The splash screen image is not installed

### ISSUE THREAD

**Issue by gtrentalancia** [drahnr/oregano#214]
### Steps to reproduce
1. Build oregano from sources
2. Install oregano using "./waf install"
3. Start oregano with the splash screen option enabled in the Options menu.

### Expected behaviour
The splash screen image should appear on application startup.

### Actual behaviour
The splash screen image DOES NOT appear on application startup.

### Configuration
All OSs. All versions up to 0.84.9.

**Comment by gtrentalancia** [comment]
Fixed here:

https://github.com/gtrentalancia/oregano/commit/beb8addf17c18875f88df47cf7864ecc0ca6f76c

**Comment by drahnr** [comment]
The splashscreen must die ASAP. It is not the 90s anymore.
