### ISSUE TITLE
Drag and Drop

### ISSUE THREAD

**Issue by drahnr** [drahnr/oregano#224]
### Steps to reproduce
1. place part
2. drag part
3. drop part

### Expected behaviour
Part should move

### Actual behaviour
Part snaps back into it's old location losing all connection dots

**Comment by gtrentalancia** [comment]
Fixed with the following two commits (see pull request #221):

https://github.com/gtrentalancia/oregano/commit/c4605d4811d8142b2f08f354bd5683d518480f24

and

https://github.com/gtrentalancia/oregano/commit/a4807a5edb64a36d47ad44cb1a242073018e5b0a
