### ISSUE TITLE
Copr for Fedora 27

### ISSUE THREAD

**Issue by remyj38** [drahnr/oregano#226]
### Steps to reproduce
1. On Fedora 27, add the copr with `dnf copr enable drahnr/oregano`
2. Try to install Oregano with `dnf install oregano`

### Expected behaviour
It should install Oregano

### Actual behaviour
The copr doesn't have support for Fedora 27 so we can't install Oregano on Fedora 27

### Configuration
**Operating system**:
```
Fedora 27 (Workstation Edition)
```

**Comment by drahnr** [comment]
Tbh I just update a few weeks ago and did not get around to test it yet, good catch! Thank you!

**Comment by drahnr** [comment]
Should be done, please re-open if it still fails for you.
